"""empty message

Revision ID: 732d04a81342
Revises: 
Create Date: 2023-07-26 11:36:38.803974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732d04a81342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flower_name', sa.String(length=64), nullable=True),
    sa.Column('flower_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.String(length=64), nullable=True),
    sa.Column('order_qty', sa.Integer(), nullable=True),
    sa.Column('flower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flower_id'], ['flower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('flower')
    # ### end Alembic commands ###
